Holimana\Domain\Day\Day:
  type: entity
  table: "`day`"
#  id:
#    id:
#      type: DayId
#      length: 255
#      primary: true
  id:
    id:
      type: DayId
      primary: true
  fields:
    date:
      type: date
      nullable: false
    status:
      type: smallint
      nullable: false
      length: 1

  manyToOne:
    user:
      targetEntity: Holimana\Domain\User\User
      inversedBy: days
      joinColumn:
        name: user_id
        referencedColumnName: id