Holimana\Domain\User\User:
  type: entity
  table: "`user`"
#  id:
#    id:
#      type: UserId
#      length: 255
#      primary: true
  id:
    id:
      type: UserId
      primary: true
  fields:
    firstname:
      type: string
      nullable: false
      length: 50
    lastname:
      type: string
      nullable: false
      length: 50
    email:
      type: string
      nullable: true
      length: 100
    password:
      type: string
      nullable: false
      length: 255
    birthday:
      type: datetime
      nullable: false
  oneToMany:
    days:
      targetEntity: Holimana\Domain\Day\Day
      mappedBy: user
      joinColumn:
        name: id
        referencedColumnName: user_id
  manyToOne:
    role:
      targetEntity: Holimana\Domain\Role\Role
      cascade: ["all"]
      inversedBy: users
      joinColumn:
        name: role_id
        referencedColumnName: id