# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Holimana}'
    Holimana\:
        resource: '../src/Holimana'
        exclude: '../src/Holimana'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #########################
    ###--EVENT PUBLISHER--###
    #########################
    Holimana\Infrastructure\Event\DomainEventPublisher:
        class: Holimana\Infrastructure\Event\DomainEventPublisher
#        arguments: ['@Holimana\Infrastructure\Event\EventProducerFactory', '%env(QUEUE_SERVICE)%']
#        calls:
#        - ['subscribe', ['@Itv\Application\DomainEvent\OrderCreatedSubscriber']]
#        - ['subscribe', ['@Itv\Application\DomainEvent\CompanyAffiliationChangedSubscriber']]

    #########################
    ###--REPOSITORY--###
    #########################
    Holimana\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository:
        class: Holimana\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository
        autowire: true
        arguments: ['@doctrine.orm.default_entity_manager', '@Holimana\Infrastructure\Event\DomainEventPublisher']


    #########################
    ###--COMMAND HANDLER--###
    #########################
    holimana.user.list_users_handler:
        class: Holimana\Application\Command\User\ListUsersHandler
        tags:
        - { name: tactician.handler, typehints: true }
        arguments:
        - '@Holimana\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository'
